/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImageParticlesRouteImport } from './routes/image-particles'
import { Route as CalenderRouteImport } from './routes/calender'
import { Route as IndexRouteImport } from './routes/index'

const ImageParticlesRoute = ImageParticlesRouteImport.update({
  id: '/image-particles',
  path: '/image-particles',
  getParentRoute: () => rootRouteImport,
} as any)
const CalenderRoute = CalenderRouteImport.update({
  id: '/calender',
  path: '/calender',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calender': typeof CalenderRoute
  '/image-particles': typeof ImageParticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calender': typeof CalenderRoute
  '/image-particles': typeof ImageParticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calender': typeof CalenderRoute
  '/image-particles': typeof ImageParticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calender' | '/image-particles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calender' | '/image-particles'
  id: '__root__' | '/' | '/calender' | '/image-particles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalenderRoute: typeof CalenderRoute
  ImageParticlesRoute: typeof ImageParticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/image-particles': {
      id: '/image-particles'
      path: '/image-particles'
      fullPath: '/image-particles'
      preLoaderRoute: typeof ImageParticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calender': {
      id: '/calender'
      path: '/calender'
      fullPath: '/calender'
      preLoaderRoute: typeof CalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalenderRoute: CalenderRoute,
  ImageParticlesRoute: ImageParticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
